build:
  version: "2"

JAVA_HOME: "8"

accounts:
  message: "Welcome to the card application"
  contactDetails:
    name: "williams - Developer"
    email: "william@devloper.com"
  onCallSupport:
    - (1800) 555-1234
    - (1800) 523-1345




