build:
  version: "4"

cards:
  message: "Welcome to the card application"
  contactDetails:
    name: "Sanjay - Developer"
    email: "sanjay@developer.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 523-1345"
